### PR TITLE
Wh working on examples pages

### PR DESCRIPTION
**Pull request by wehuang16**
Wh working on ".md" examples pages to add G36 extension equipment

### CODE REVIEW

**Comment by wehuang16** [comment]
Please use the "guideline36-2021-4.2.md" file from open223:main to resolve the conflict

**Comment by gtfierro** [comment]
Please add the models to the `_toc.yaml` file and make sure that the capitalization of the .ttl files and .md files is the same

**Comment by gtfierro** [comment]
Please also use the same naming scheme for guideline 36 files as has been established in the repo.

@wehuang16 will you be able to handle fixing these issues this morning? If you don't have time I can do it

**Comment by gtfierro** [comment]
Currently working on fixing these examples

**Pull request merged**
