### PR TITLE
add G36 4.2

### PR DESCRIPTION
**Pull request by MatthewSteen**
For Docs Tutorial 1. FYI @lazlop.

### CODE REVIEW

**Comment by gtfierro** [comment]
I just pushed a README file describing how to add a model to this repository. Committing the file to the `models/` directory will be enough to present it online under "https://models.open223.info/<filename>.ttl"

**Comment by MatthewSteen** [comment]
@gtfierro great, I'll work on finishing this then. A couple questions...

1. Naming Convention
   1. same as 223 GitLAB?
   2. `guideline36-2021-4.2.ttl`?
   3. ?
2. Folders. Should we organize into...
   - `ashrae/`
   - `lbnl/`
   - `nrel/`

**Comment by gtfierro** [comment]
> @gtfierro great, I'll work on finishing this then. A couple questions...
> 
> 1. Naming Convention
>    
>    1. same as 223 GitLAB?

The code here is agnostic to the naming convention. As long as the file names match across the different components (`.md`, `.ttl`, etc), we are good to go. Let me know if you hit any bugs or unexpected behavior. The GitHub Action should take care of all the builds so you don't need to run this locally

>    2. `guideline36-2021-4.2.ttl`?
>    3. ?
> 2. Folders. Should we organize into...
>    
>    * `ashrae/`
>    * `lbnl/`
>    * `nrel/`

We can, but this might be more organization than we need yet. I think differentiating between building/system is enough for now. The source of the example probably doesn't matter as much

**Comment by MatthewSteen** [comment]
@gtfierro ready. Note I changed the `book.yml` file to run on PRs too. It probably _shouldn't_ deploy (if statement) just successfully run `jb build .`.

**Comment by gtfierro** [comment]
Good change! Thanks for handling that

**Pull request merged**
