### PR TITLE
Harmonize both pritoni models

### PR DESCRIPTION
**Pull request by michaelpoplawskipnnl**
Harmonized descriptions for both "Pritoni" models.
Began implementing proposals described in Issue #17 
Edited .ttl and .md file names (only), and .md content.
Did NOT edit .ttl files to incorporate contribution and method metadata via DC/Terms.
Waiting for @steveraysteveray proposal for what DC/Terms concepts to use.

### CODE REVIEW

**Comment by steveraysteveray** [comment]
Several comments.

1. I made some cosmetic changes to this branch as per my commits above.
2. With the agreement of the group, I suggest we make the introduction section of the .md files the same as the rdfs:comment value of the respective .ttl files, to reduce maintenance tasks.
3. Since we already use rdfs:comment as a property of each instance of a data ontology, we don't need an additional relation for a general description within each .ttl file. For additional metadata to be attached to each data .ttl file/graph (associated with the ontology instance) I suggest the following properties from the dcterms ontology:

- [license](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/license), with just a literal value of a string satisfying ASHRAE's licensing requirements
- [rights holder](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/rightsHolder), with some text identifying the ASHRAE legal entity

...and if we decide to do this:
- [contributor](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/contributor) for any names of those who contributed to that particular graph (coded as multiple triples).

Regarding the schema and rule files, I suggest we do the same thing, although we will need to be careful with the rdfs:comment values if we merge them all into a single graph/file for distribution.

**Comment by michaelpoplawskipnnl** [comment]
1. @steveraysteveray I reviewed and like your cosmetic changes. I made a few more cosmetic changes that hopefully further aid in understanding that we have multiple models for the same building.
2. @steveraysteveray if you're good with the current status, I think we could merge the current version of this branch, and add the dc/terms triples to the .ttl files later.

**Comment by steveraysteveray** [comment]
Agreed, and done!

**Comment by michaelpoplawskipnnl** [comment]
@steveraysteveray one more thing to add to your list (#2 and #3 above):
I might suggest we make the instance prefix in our models match the file name
e.g., `` @prefix bdg1-1: <uri> ``

**Comment by steveraysteveray** [comment]
Sure, as long as the filenames don't get too long.

By the way, why bdg1 and not bldg1?

**Comment by michaelpoplawskipnnl** [comment]
I don't care bdg or bldg - just trying to save a character, in the spirit of your file name getting too long comment 😌

**Pull request merged**
